title: String Extension And Debug
description : Easy String Interpolation with color style and size With Debug Methods
tagline : Easy String Interpolation with color style and size With Debug Methods
theme: jekyll-theme-merlot
